package homework15;

public enum EnvType {
    LOCAL_DEFAULT,
    REMOTE_DEFAULT,
    LOCAL_CHROME,
    REMOTE_CHROME,
    LOCAL_FIREFOX,
    REMOTE_FIREFOX,
    JENKINS_CHROME,
    JENKINS_FIREFOX;
}
